# Site settings
title: 
header-img: img/home-bg.png
email: cbronzo@mac.com
copyright_name: cbronzo
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cbronzo
learn_profile: cbronzo
email_username: cbronzo@mac.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
